algorithm: ford_fulkerson_mincut
runs:
  num_runs: 25
  hp_space: ff_mc_small
  batch_size: 32
  early_stop: true
  early_stop_patience: 20
  train_steps: 5000
  verbose: true
  log_every: 100
experiment:
  name: mc
  higher_is_better: false
  num_valid_trials: 1
